
// This file has been generated by the GUI designer. Do not modify.
namespace GTKMapDemo
{
	public partial class MainWindow
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button btnUp;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.DrawingArea picMapCanvas;

		private global::Gtk.Label GtkLabel1;

		private global::Gtk.Button btnLeft;

		private global::Gtk.Button btnRight;

		private global::Gtk.Button btnZoomIn;

		private global::Gtk.Button btnDown;

		private global::Gtk.Button btnZoomOut;

		private global::Gtk.Entry txtAddress;

		private global::Gtk.Button btnGo;

		private global::Gtk.Entry txtAddress1;

		private global::Gtk.Entry txtAddress2;

		private global::Gtk.Button btnGetDirection;

		private global::Gtk.Label label1;

		private global::Gtk.ComboBox cboMapType;

		private global::Gtk.Button btnExit;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GTKMapDemo.MainWindow
			this.WidthRequest = 1196;
			this.HeightRequest = 936;
			this.Name = "GTKMapDemo.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Guidebee Map Demo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.AllowGrow = false;
			this.DefaultWidth = 1196;
			this.DefaultHeight = 936;
			// Container child GTKMapDemo.MainWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 1196;
			this.fixed1.HeightRequest = 936;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnUp = new global::Gtk.Button ();
			this.btnUp.WidthRequest = 88;
			this.btnUp.HeightRequest = 40;
			this.btnUp.CanFocus = true;
			this.btnUp.Name = "btnUp";
			this.btnUp.UseUnderline = true;
			this.btnUp.Label = global::Mono.Unix.Catalog.GetString ("Up");
			this.fixed1.Add (this.btnUp);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnUp]));
			w1.X = 965;
			w1.Y = 12;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.WidthRequest = 818;
			this.frame3.HeightRequest = 876;
			this.frame3.Name = "frame3";
			this.frame3.LabelYalign = 0f;
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.picMapCanvas = new global::Gtk.DrawingArea ();
			this.picMapCanvas.WidthRequest = 768;
			this.picMapCanvas.HeightRequest = 768;
			this.picMapCanvas.Events = ((global::Gdk.EventMask)(274));
			this.picMapCanvas.Name = "picMapCanvas";
			this.GtkAlignment.Add (this.picMapCanvas);
			this.frame3.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel1;
			this.fixed1.Add (this.frame3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame3]));
			w4.X = 20;
			w4.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnLeft = new global::Gtk.Button ();
			this.btnLeft.WidthRequest = 88;
			this.btnLeft.HeightRequest = 40;
			this.btnLeft.CanFocus = true;
			this.btnLeft.Name = "btnLeft";
			this.btnLeft.UseUnderline = true;
			this.btnLeft.Label = global::Mono.Unix.Catalog.GetString ("Left");
			this.fixed1.Add (this.btnLeft);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnLeft]));
			w5.X = 852;
			w5.Y = 59;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnRight = new global::Gtk.Button ();
			this.btnRight.WidthRequest = 88;
			this.btnRight.HeightRequest = 40;
			this.btnRight.CanFocus = true;
			this.btnRight.Name = "btnRight";
			this.btnRight.UseUnderline = true;
			this.btnRight.Label = global::Mono.Unix.Catalog.GetString ("Right");
			this.fixed1.Add (this.btnRight);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnRight]));
			w6.X = 1078;
			w6.Y = 59;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnZoomIn = new global::Gtk.Button ();
			this.btnZoomIn.WidthRequest = 88;
			this.btnZoomIn.HeightRequest = 40;
			this.btnZoomIn.CanFocus = true;
			this.btnZoomIn.Name = "btnZoomIn";
			this.btnZoomIn.UseUnderline = true;
			this.btnZoomIn.Label = global::Mono.Unix.Catalog.GetString ("Zoom In");
			this.fixed1.Add (this.btnZoomIn);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnZoomIn]));
			w7.X = 853;
			w7.Y = 105;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnDown = new global::Gtk.Button ();
			this.btnDown.WidthRequest = 88;
			this.btnDown.HeightRequest = 40;
			this.btnDown.CanFocus = true;
			this.btnDown.Name = "btnDown";
			this.btnDown.UseUnderline = true;
			this.btnDown.Label = global::Mono.Unix.Catalog.GetString ("Down");
			this.fixed1.Add (this.btnDown);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnDown]));
			w8.X = 965;
			w8.Y = 105;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnZoomOut = new global::Gtk.Button ();
			this.btnZoomOut.WidthRequest = 88;
			this.btnZoomOut.HeightRequest = 40;
			this.btnZoomOut.CanFocus = true;
			this.btnZoomOut.Name = "btnZoomOut";
			this.btnZoomOut.UseUnderline = true;
			this.btnZoomOut.Label = global::Mono.Unix.Catalog.GetString ("ZoomOut");
			this.fixed1.Add (this.btnZoomOut);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnZoomOut]));
			w9.X = 1077;
			w9.Y = 105;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtAddress = new global::Gtk.Entry ();
			this.txtAddress.WidthRequest = 218;
			this.txtAddress.HeightRequest = 24;
			this.txtAddress.CanFocus = true;
			this.txtAddress.Name = "txtAddress";
			this.txtAddress.IsEditable = true;
			this.txtAddress.InvisibleChar = '●';
			this.fixed1.Add (this.txtAddress);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtAddress]));
			w10.X = 852;
			w10.Y = 159;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnGo = new global::Gtk.Button ();
			this.btnGo.WidthRequest = 88;
			this.btnGo.HeightRequest = 40;
			this.btnGo.CanFocus = true;
			this.btnGo.Name = "btnGo";
			this.btnGo.UseUnderline = true;
			this.btnGo.Label = global::Mono.Unix.Catalog.GetString ("Go");
			this.fixed1.Add (this.btnGo);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnGo]));
			w11.X = 1077;
			w11.Y = 152;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtAddress1 = new global::Gtk.Entry ();
			this.txtAddress1.WidthRequest = 305;
			this.txtAddress1.HeightRequest = 23;
			this.txtAddress1.CanFocus = true;
			this.txtAddress1.Name = "txtAddress1";
			this.txtAddress1.IsEditable = true;
			this.txtAddress1.InvisibleChar = '●';
			this.fixed1.Add (this.txtAddress1);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtAddress1]));
			w12.X = 853;
			w12.Y = 217;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtAddress2 = new global::Gtk.Entry ();
			this.txtAddress2.WidthRequest = 305;
			this.txtAddress2.HeightRequest = 23;
			this.txtAddress2.CanFocus = true;
			this.txtAddress2.Name = "txtAddress2";
			this.txtAddress2.IsEditable = true;
			this.txtAddress2.InvisibleChar = '●';
			this.fixed1.Add (this.txtAddress2);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtAddress2]));
			w13.X = 853;
			w13.Y = 263;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnGetDirection = new global::Gtk.Button ();
			this.btnGetDirection.WidthRequest = 157;
			this.btnGetDirection.HeightRequest = 40;
			this.btnGetDirection.CanFocus = true;
			this.btnGetDirection.Name = "btnGetDirection";
			this.btnGetDirection.UseUnderline = true;
			this.btnGetDirection.Label = global::Mono.Unix.Catalog.GetString ("Get Direction");
			this.fixed1.Add (this.btnGetDirection);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnGetDirection]));
			w14.X = 1001;
			w14.Y = 313;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.WidthRequest = 64;
			this.label1.HeightRequest = 17;
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Map Type");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w15.X = 857;
			w15.Y = 580;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cboMapType = global::Gtk.ComboBox.NewText ();
			this.cboMapType.AppendText (global::Mono.Unix.Catalog.GetString ("Google Map"));
			this.cboMapType.AppendText (global::Mono.Unix.Catalog.GetString ("Google Map China"));
			this.cboMapType.AppendText (global::Mono.Unix.Catalog.GetString ("Microsoft Map "));
			this.cboMapType.AppendText (global::Mono.Unix.Catalog.GetString ("Microsoft Map China"));
			this.cboMapType.AppendText (global::Mono.Unix.Catalog.GetString ("Microsoft Satellite"));
			this.cboMapType.AppendText (global::Mono.Unix.Catalog.GetString ("Micrsoft Hybrid"));
			this.cboMapType.WidthRequest = 234;
			this.cboMapType.HeightRequest = 25;
			this.cboMapType.Name = "cboMapType";
			this.cboMapType.Active = 1;
			this.fixed1.Add (this.cboMapType);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cboMapType]));
			w16.X = 931;
			w16.Y = 576;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnExit = new global::Gtk.Button ();
			this.btnExit.WidthRequest = 64;
			this.btnExit.HeightRequest = 40;
			this.btnExit.CanFocus = true;
			this.btnExit.Name = "btnExit";
			this.btnExit.UseUnderline = true;
			this.btnExit.Label = global::Mono.Unix.Catalog.GetString ("Exit");
			this.fixed1.Add (this.btnExit);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnExit]));
			w17.X = 1101;
			w17.Y = 801;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnUp.Clicked += new global::System.EventHandler (this.OnBtnUpClicked);
			this.picMapCanvas.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnPicMapCanvasMotionNotifyEvent);
			this.picMapCanvas.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnPicMapCanvasButtonPressEvent);
			this.btnLeft.Clicked += new global::System.EventHandler (this.OnBtnLeftClicked);
			this.btnRight.Clicked += new global::System.EventHandler (this.OnBtnRightClicked);
			this.btnZoomIn.Clicked += new global::System.EventHandler (this.OnBtnZoomInClicked);
			this.btnDown.Clicked += new global::System.EventHandler (this.OnBtnDownClicked);
			this.btnZoomOut.Clicked += new global::System.EventHandler (this.OnBtnZoomOutClicked);
			this.btnGo.Clicked += new global::System.EventHandler (this.OnBtnGoClicked);
			this.btnGetDirection.Clicked += new global::System.EventHandler (this.OnBtnGetDirectionClicked);
			this.cboMapType.Changed += new global::System.EventHandler (this.OnCboMapTypeChanged);
			this.btnExit.Clicked += new global::System.EventHandler (this.OnBtnExitClicked);
		}
	}
}
